Config.Client.Veicoli.veicoliAff = {
	biciclette = {
		{name = "Whippet Racemoto", 	price = 1750, description = "", model = "tribike"},
		{name = "Cruiser", 				price = 950, description = "", model = "cruiser"},
		{name = "BMX", 					price = 800, description = "", model = "BMX"},
		{name = "Scorcher", 			price = 1000, description = "", model = "SCORCHER"},
		
	},
	macchineGeneric = {
		{name = "Blista", 				price = 4000, description = "Blista", model = "blista"},
	},
	macchineMedium = {
		{name = "Neon", 				price = 40000, description = "", model = "neon"},
	},
	macchineSuper = {
		{name = "Zentorno",				price = 400000, description = "", model = "zentorno"},
		{name = "Tezeract",				price = 400000, description = "", model = "tezeract"},
	},
	motoGeneric = {
		{name = "Faggio", 				price = 4000, description = "", model = "faggio2"},
		{name = "Faggio Sport", 		price = 6500, description = "", model = "faggio"},
		{name = "Faggio Mod", 			price = 8000, description = "", model = "Faggio3"},
		{name = "Ratbike", 				price = 15000, description = "", model = "Ratbike"},
		{name = "Sanchez", 				price = 20000, description = "", model = "sanchez"},
		{name = "Vader", 				price = 29000, description = "", model = "vader"},
		{name = "Carbon RS", 			price = 32000, description = "", model = "carbonrs"},
		{name = "Akuma", 				price = 43000, description = "", model = "akuma"},
		{name = "Hexer", 				price = 43000, description = "", model = "hexer"},
		{name = "PCJ-600", 				price = 47000, description = "", model = "pcj"},
	},
	motoMedium = {
		{name = "Ruffian", 				price = 50000, description = "", model = "ruffian"},
		{name = "Nemesis", 				price = 51000, description = "", model = "nemesis"},
		{name = "Bagger", 				price = 55000, description = "", model = "bagger"},
		{name = "Daemon", 				price = 56000, description = "", model = "daemon"},
		{name = "Sovereign", 			price = 60000, description = "", model = "sovereign"},
		{name = "Thrust", 				price = 60000, description = "", model = "thrust"},
		{name = "Double T", 			price = 63000, description = "", model = "double"},
		{name = "Daemon DLC", 			price = 65000, description = "", model = "Daemon2"},
		{name = "Lectro", 				price = 70000, description = "", model = "lectro"},
		{name = "Enduro", 				price = 75000, description = "", model = "enduro"},
		{name = "Wolfsbane", 			price = 75000, description = "", model = "wolfsbane"},
		{name = "Esskey", 				price = 78500, description = "", model = "Esskey"},
		{name = "FCR1000", 				price = 87200, description = "", model = "FCR"},
		{name = "Avarus", 				price = 88000, description = "", model = "Avarus"},
		{name = "Cliffhanger",			price = 90000, description = "", model = "cliffhanger"},
		{name = "Vortex", 				price = 92000, description = "", model = "Vortex"},
		{name = "Diablous", 			price = 95000, description = "", model = "Diablous"},
		{name = "Nightblade", 			price = 95200, description = "", model = "Nightblade"},
		{name = "FCR1000 Custom", 		price = 99500, description = "", model = "FCR2"},
	},
	motoSuper = {
		{name = "Chimera", 				price = 100000, description = "", model = "Chimera"},
		{name = "Diablous Custom", 		price = 115000, description = "", model = "Diablous2"},
		{name = "HAKUCHOU Drag", 		price = 650000, description = "", model = "Hakuchou2"},
		{name = "Shotaro", 				price = 1200000, description = "", model = "Shotaro"},
		{name = "Zombie Bobber", 		price = 103000, description = "", model = "Zombiea"},
		{name = "Zombie Chopper",		price = 110000, description = "", model = "Zombieb"},
		{name = "Bati 801", 			price = 102000, description = "", model = "bati"},
		{name = "Bati 801RR",			price = 125000, description = "", model = "bati2"},
		{name = "Gargoyle", 			price = 120000, description = "", model = "gargoyle"},
		{name = "Hakuchou", 			price = 175000, description = "", model = "hakuchou"},
		{name = "Innovation", 			price = 100000, description = "", model = "innovation"},
		{name = "Sanctus", 				price = 280000, description = "", model = "sanctus"},
		{name = "Vindicator", 			price = 210000, description = "", model = "vindicator"},
	},	
}