//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLastPlanet.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheLastPlanet.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///   &quot;Main&quot;:{
        ///      &quot;AfkTimeout&quot;:300,
        ///      &quot;AutoSavingInterval&quot;:180000,
        ///      &quot;PingThreshold&quot;:300,
        ///      &quot;MaxPlayerNameLength&quot;:24,
        ///      &quot;EnableVoiceChat&quot;:false,
        ///      &quot;DiscordNotificationInterval&quot;:900000,
        ///      &quot;MaxMenuOptionCount&quot;:7,
        ///      &quot;SpawnProtectionTime&quot;:3000,
        ///      &quot;KillstreakTimeout&quot;:5000,
        ///      &quot;MinPrestigeRank&quot;:100,
        ///      &quot;MaxPrestige&quot;:10,
        ///      &quot;PrestigeBonus&quot;:0.035,
        ///      &quot;CrewInvitationTimeout&quot;:10000,
        ///      &quot;SpecialVehicleMinRank&quot;:5,
        ///      &quot;Gta2Cam&quot;:{
        ///         &quot;Min&quot;:24.0,
        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string Client_FreeRoam {
            get {
                return ResourceManager.GetString("Client_FreeRoam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///    &quot;Main&quot;:{
        ///       &quot;NomeServer&quot;:&quot;The Last Galaxy&quot;,
        ///       &quot;DiscordAppId&quot;:&quot;625350962776637491&quot;,
        ///       &quot;DiscordRichPresenceAsset&quot;:&quot;majoras2&quot;,
        ///       &quot;PassengerDriveBy&quot;:true,
        ///       &quot;KickWarning&quot;:true,
        ///       &quot;AFKCheckTime&quot;:600,
        ///       &quot;Firstcoords&quot;:{
        ///          &quot;X&quot;:1.0,
        ///          &quot;Y&quot;:1.0,
        ///          &quot;Z&quot;:1.0,
        ///          &quot;W&quot;:1.0,
        ///          &quot;IsNormalized&quot;:false,
        ///          &quot;IsZero&quot;:false
        ///       },
        ///       &quot;ReviveReward&quot;:700,
        ///       &quot;EarlyRespawn&quot;:true,
        ///       &quot;EarlyRespawnFine&quot;:false,
        ///       &quot;E [stringa troncata]&quot;;.
        /// </summary>
        internal static string Client_RolePlay {
            get {
                return ResourceManager.GetString("Client_RolePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///  &quot;Main&quot;: {
        ///    &quot;NomeServer&quot;: &quot;The Last Planet&quot;,
        ///    &quot;WebHookLog&quot;: null,
        ///    &quot;WebHookAnticheat&quot;: null,
        ///    &quot;notWhitelisted&quot;: &quot;SHIELD 2.0:\nNon sei autorizzato a entrare su questo server!\nChiedi l&apos;autorizzazione sul canale Discord di Manups4e (discord.gg/n4ep9Fq) nella sezione dedicata!.&quot;,
        ///    &quot;EnableAntiSpam&quot;: true,
        ///    &quot;PlayersToStartRocade&quot;: 64,
        ///    &quot;PingMax&quot;: 500,
        ///    &quot;SalvataggioTutti&quot;: 10,
        ///    &quot;RentPricePompeDiBenzina&quot;: 5000,
        ///    &quot;RentPriceNegozi&quot;: 5000,
        ///    &quot;RuoloWhitelistato&quot;: &quot;Test&quot;,        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string ServerConfig {
            get {
                return ResourceManager.GetString("ServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///    &quot;Main&quot;:{
        ///        &quot;Veicoli&quot;:{
        ///            &quot;gasstations&quot;:[
        ///                {
        ///                    &quot;pos&quot;:{
        ///                        &quot;X&quot;:49.41872,
        ///                        &quot;Y&quot;:2778.793,
        ///                        &quot;Z&quot;:58.04395,
        ///                        &quot;IsNormalized&quot;:false,
        ///                        &quot;IsZero&quot;:false
        ///                    },
        ///                    &quot;pumps&quot;:[
        ///                        {
        ///                            &quot;X&quot;:49.49921,
        ///                            &quot;Y&quot;:2778.912,
        ///                          [stringa troncata]&quot;;.
        /// </summary>
        internal static string SharedConfig {
            get {
                return ResourceManager.GetString("SharedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [
        ///  {
        ///    &quot;Name&quot;: &quot;WEAPON_UNARMED&quot;,
        ///    &quot;Label&quot;: {
        ///      &quot;Hash&quot;: 1122011548,
        ///      &quot;Name&quot;: &quot;WT_UNARMED&quot;
        ///    },
        ///    &quot;UintHash&quot;: 2725352035,
        ///    &quot;IntHash&quot;: -1569615261,
        ///    &quot;DlcName&quot;: &quot;TitleUpdate&quot;,
        ///    &quot;Category&quot;: &quot;GROUP_UNARMED&quot;,
        ///    &quot;Description&quot;: null,
        ///    &quot;Tints&quot;: [
        ///      {
        ///        &quot;Index&quot;: 0,
        ///        &quot;Label&quot;: {
        ///          &quot;Hash&quot;: 3773086928,
        ///          &quot;Name&quot;: &quot;WM_TINT0&quot;
        ///        }
        ///      },
        ///      {
        ///        &quot;Index&quot;: 1,
        ///        &quot;Label&quot;: {
        ///          &quot;Hash&quot;: 3271590152,
        ///          &quot;Name&quot; [stringa troncata]&quot;;.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
    }
}
